					</div>
					<footer>
						<a id="backToTop" class="toTop" href="javascript:void(0);" title="Åter till toppen av sidan">&#8673; Till toppen</a>
						<div style="margin-left:-3.5em;">
							<a href="tel:+46771414300" class="customerService">
								<small>Kundservice</small><br/>0771 - 41 43 00
							</a>
						</div>
						<p>
							<a href="#">Vanliga frågor och svar</a>
							<a href="#">Hittegods</a>
							<a href="#">Kontakta Västtrafik</a>
							<a href="#">In English</a>
						</p>
						<span><a href="#">Ansvarig utgivare</a> | <a href="#">Om cookies</a></span>
						<a href="http://www.vasttrafik.se?fromMobileWeb" class="toDesktop">Gå till västtrafik.se anpassad för dator &raquo;</a>
					</footer>
				</div>
			</div>
		</div>

		<script src="js/sidebarEffects.js"></script>
        <!--script src="js/helper.js"></script-->
		<script src="js/main.js"></script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <!-- script>
            var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
            g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
            s.parentNode.insertBefore(g,s)}(document,"script"));
        </script -->
    </body>
</html>
